ospin-web-dev/FCTGraph

package-lock.json

BREAKING CHANGES: testing v1 deploy

synx lock and package

---

package.json

BREAKING CHANGE: this is the body to trigger a major version

perf(testdeploy): test auto deploy

---

README.md

fix(node-version): trigger release for node version

fix(node-version): trigger release for node version

---

src/dataStreams/DataStream.js
src/seeders/slots/OutSlotSeeder.js
src/slots/Slot.js
test/slots/Slot.test.js

- data streams now serialize back to data objects
- averaging window size set to 0 minimum no null required

fix: datastreams-serialization-and-avg-wdw-size

---

README.md
src/dataStreams/DataStream.js
src/fctGraph/FCTGraph.js
src/seeders/dataStreams/DataStreamSeeder.js
src/seeders/slots/InSlotSeeder.js
src/seeders/slots/SlotSeeder.js
src/slots/InSlot.js
test/dataStreams/DataStream.test.js
test/slots/Slot.test.js

fix: avg windowing size default to 0

---

README.md
package.json

fix(deploy): junge

---

src/functionalities/Functionality.js
src/seeders/functionalities/HeaterActuatorSeeder.js
src/seeders/functionalities/PIDControllerSeeder.js
test/functionalities/Functionality.test.js

feat: 59 get connected functionalities

---

README.md

see title!
also fixes minor inaccuracy in import

docs: adds instructions for FCTGraphUtils

---

README.md
src/fctGraph/FCTGraph.js
src/fctGraph/Utils/mutators/addPushInFctForInSlotWhichHasNone.js
src/fctGraph/Utils/mutators/addPushOutFctForOutSlotWhichHasNone.js
src/functionalities/Functionality.js
src/functionalities/factories/FunctionalityFactory.js
src/mixins/instanceMixins/JOIous.js
src/slots/Slot.js
test/fctGraph/FCTGraph.test.js
test/functionalities/Functionality.test.js
test/functionalities/factories/FunctionalityFactory.test.js
test/mixins/instanceMixins/JOIous.test.js
test/slots/FloatInSlot.test.js
test/slots/IntegerInSlot.test.js
test/slots/Slot.test.js

- no longer does joi assertions on all construction (for speed)
- adds convenience method for getting all push out nodes
- slots can now disconnect from other slots

feat: several - see message

---

README.md
src/functionalities/Functionality.js
src/slots/Slot.js

feat: adds display type for controller params

---

package-lock.json
src/fctGraph/Utils/predicates/fctsAreFunctionallyEqual.js
src/functionalities/Functionality.js
src/seeders/functionalities/FunctionalitySeeder.js
src/slots/Slot.js
src/utils/ObjUtils.js
test/fctGraph/seeds/connectedFCTGraphData.js
test/fctGraph/utils/predicates/fctAreFunctionallyEqual.test.js

closes #100 💯 
PR has two goals other than adding the specific behavior of checking compatibility:
1. give an open/closed pattern to extend this template derivation from inheriting children (in the exact same way that `serialize` works). Hopefully this will make it easy to selectively exclude values from subTypes as it becomes necessary
2. provide 1:1 behavior with felix's existing method in Hambda, documented here:
```js
static haveEqualFunctionalities(SVFCTs1, SVFCTs2) {
if (SVFCTs1.length !== SVFCTs2.length) {
return false
}
const sortedSVFCTs = [{ ...SVFCTs1 }, { ...SVFCTs2 }].map(SVFCTs => {
const sortedFcts = ArrayUtils.sortObjectsByKeyValue(SVFCTs.supportedVirtualFunctionalities, 'subType')
const fctsWithSortedSlots = sortedFcts.map(fct => {
fct.slots = …
```

feat:  compare fct functionally

---

src/functionalities/HeidolphPumpByTorqueHysteresisController.js
src/functionalities/HysteresisController.js
src/functionalities/factories/FunctionalityFactory.js
src/functionalities/index.js
src/seeders/functionalities/HeidolphPumpByTorqueHysteresisControllerSeeder.js
src/seeders/functionalities/HysteresisControllerSeeder.js
src/seeders/functionalities/index.js
test/functionalities/factories/FunctionalityFactory.test.js
test/index.test.js

feat: adds a two new controller subTypes to the fcts API

---

src/functionalities/Functionality.js
src/slots/InSlot.js
src/slots/OutSlot.js
src/slots/Slot.js
test/functionalities/Functionality.test.js
test/slots/Slot.test.js

closes #106
the first part for looking up the derived unit of a slot
For the exact mapping on special functionalities like Controllers, we need a list of slot names from the firmware

feat: 106 slot unit derivation

---

src/slots/OneOfInSlot.js
test/slots/OneOfInSlot.test.js

fix: oneOf inSlots auto generate empty selectOptions array
closes #115

fix: oneOf inSlots auto generate empty selectOptions array

---

README.md

feat!: trigger a release for the last commit

---

README.md

BREAKING CHANGE: see commit history

feat: major release, see history

---

README.md

to trigger pipeline for accurate test coverage

fix: trigger pipeline

---

src/functionalities/KernRS232Scale.js
src/functionalities/factories/FunctionalityFactory.js
src/functionalities/index.js
src/seeders/functionalities/KernRS232ScaleSeeder.js
src/seeders/functionalities/index.js
test/functionalities/factories/FunctionalityFactory.test.js
test/index.test.js

closes #150 
The boilerplate code annoys me. I will refactor it asap, but firmware needs the new subType by tomorrow.

feat: adds a new subType for sensors: KernRS232Scale

---

src/fctGraph/FCTGraph.js
test/fctGraph/FCTGraph.test.js

fix: Optimize schemas

---

src/seeders/slots/SlotSeeder.js
src/slots/Slot.js
test/fctGraph/FCTGraph.test.js
test/slots/Slot.test.js

feat: Add number datatype 
